-- whatsapp-flow-engine-service-v3 - schema DDL
--
-- This service owns its own Postgres database, isolated from whatsapp-flow-engine-service (V2)
-- and everything else on the instance - no tables are shared with anyone. Run once, before the
-- app is started (spring.jpa.hibernate.ddl-auto is "validate", it never creates anything itself).
--
-- 1. Create the database (run as a superuser / role that can CREATE DATABASE, connected to
--    "postgres" or any other existing database - NOT to chatbot_v3 itself, since it doesn't
--    exist yet):
--
--      CREATE DATABASE chatbot_v3 OWNER chatbot;
--
--    Skip this step if "chatbot_v3" already exists (e.g. it was created for you).
--
-- 2. Run this file against that database:
--
--      psql "postgresql://chatbot:chatbot@localhost:5434/chatbot_v3" -f db/01_schema.sql
--
-- Idempotent to re-run - every statement is guarded by IF NOT EXISTS.

CREATE SCHEMA IF NOT EXISTS flow_engine;

SET search_path TO flow_engine;

CREATE TABLE IF NOT EXISTS flow_engine.flow_node (
    node_id bigint NOT NULL,
    back_target_node_id bigint,
    flow_code character varying(50) NOT NULL,
    node_type character varying(20) NOT NULL,
    screen_id character varying(100) NOT NULL,
    action_code character varying(50),
    CONSTRAINT flow_node_pkey PRIMARY KEY (node_id),
    CONSTRAINT flow_node_screen_id_key UNIQUE (screen_id),
    CONSTRAINT flow_node_node_type_check CHECK (
        (node_type)::text = ANY (ARRAY['SCREEN', 'TERMINAL']::text[])
    )
);

CREATE TABLE IF NOT EXISTS flow_engine.flow_transition (
    transition_id bigint GENERATED BY DEFAULT AS IDENTITY,
    display_order integer NOT NULL,
    from_node_id bigint NOT NULL,
    option_label character varying(255),
    option_value character varying(100),
    to_node_id bigint NOT NULL,
    CONSTRAINT flow_transition_pkey PRIMARY KEY (transition_id)
);

CREATE TABLE IF NOT EXISTS flow_engine.flow_session (
    flow_token character varying(64) NOT NULL,
    completed_at timestamp(6) with time zone,
    context jsonb NOT NULL,
    current_node_id bigint NOT NULL,
    last_interaction_at timestamp(6) with time zone NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    wa_id character varying(32) NOT NULL,
    CONSTRAINT flow_session_pkey PRIMARY KEY (flow_token),
    CONSTRAINT flow_session_status_check CHECK (
        (status)::text = ANY (ARRAY['OPENED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED']::text[])
    )
);

CREATE TABLE IF NOT EXISTS flow_engine.flow_node_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action_type character varying(20) NOT NULL,
    customer_id character varying(32) NOT NULL,
    flow_token character varying(64) NOT NULL,
    node_id bigint NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    request_data jsonb,
    response_data jsonb,
    screen_id character varying(100) NOT NULL,
    selected_value character varying(100),
    CONSTRAINT flow_node_history_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_flow_session_wa_id ON flow_engine.flow_session (wa_id);
CREATE INDEX IF NOT EXISTS idx_flow_node_history_flow_token ON flow_engine.flow_node_history (flow_token);
